export default [
  { features: [], classes: [] },
  { features: ["biology"], classes: [] },
  { features: ["politics"], classes: ["politics"] },
  { features: ["biology", "politics"], classes: ["politics"] },
  { features: ["activism"], classes: ["activism"] },
  { features: ["biology", "activism"], classes: ["activism"] },
  { features: ["politics", "activism"], classes: ["politics", "activism"] },
  { features: ["biology", "politics", "activism"], classes: ["politics", "activism"] },
  { features: ["climate"], classes: ["climate"] },
  { features: ["biology", "climate"], classes: ["climate"] },
  { features: ["politics", "climate"], classes: ["climate", "politics"] },
  { features: ["biology", "politics", "climate"], classes: ["climate", "politics"] },
  { features: ["activism", "climate"], classes: ["climate", "activism", "politics"] },
  { features: ["biology", "activism", "climate"], classes: ["climate", "activism", "politics"] },
  { features: ["politics", "activism", "climate"], classes: ["climate", "politics", "activism"] },
  { features: ["biology", "politics", "activism", "climate"], classes: ["climate", "politics", "activism"] },
  { features: ["nature"], classes: ["nature"] },
  { features: ["biology", "nature"], classes: ["nature"] },
  { features: ["politics", "nature"], classes: ["nature", "politics"] },
  { features: ["biology", "politics", "nature"], classes: ["nature", "politics"] },
  { features: ["activism", "nature"], classes: ["nature", "activism"] },
  { features: ["biology", "activism", "nature"], classes: ["nature", "activism"] },
  { features: ["politics", "activism", "nature"], classes: ["nature", "politics", "activism"] },
  { features: ["biology", "politics", "activism", "nature"], classes: ["nature", "politics", "activism"] },
  { features: ["climate", "nature"], classes: ["nature", "climate", "politics"] },
  { features: ["biology", "climate", "nature"], classes: ["nature", "climate", "politics"] },
  { features: ["politics", "climate", "nature"], classes: ["nature", "climate", "politics", "activism"] },
  { features: ["biology", "politics", "climate", "nature"], classes: ["nature", "climate", "politics", "activism"] },
  { features: ["activism", "climate", "nature"], classes: ["nature", "climate", "activism", "politics"] },
  { features: ["biology", "activism", "climate", "nature"], classes: ["nature", "climate", "activism", "politics"] },
  { features: ["politics", "activism", "climate", "nature"], classes: ["nature", "climate", "politics", "activism"] },
  { features: ["biology", "politics", "activism", "climate", "nature"], classes: ["nature", "climate", "politics", "activism"] },
  { features: ["condition"], classes: ["condition"] },
  { features: ["biology", "condition"], classes: ["condition"] },
  { features: ["politics", "condition"], classes: ["politics", "condition"] },
  { features: ["biology", "politics", "condition"], classes: ["politics", "condition"] },
  { features: ["activism", "condition"], classes: ["activism", "condition"] },
  { features: ["biology", "activism", "condition"], classes: ["activism", "condition"] },
  { features: ["politics", "activism", "condition"], classes: ["politics", "activism", "condition"] },
  { features: ["biology", "politics", "activism", "condition"], classes: ["politics", "activism", "condition"] },
  { features: ["climate", "condition"], classes: ["climate", "condition"] },
  { features: ["biology", "climate", "condition"], classes: ["climate", "condition"] },
  { features: ["politics", "climate", "condition"], classes: ["climate", "politics", "condition"] },
  { features: ["biology", "politics", "climate", "condition"], classes: ["climate", "politics", "condition"] },
  { features: ["activism", "climate", "condition"], classes: ["climate", "activism", "condition", "politics"] },
  { features: ["biology", "activism", "climate", "condition"], classes: ["climate", "activism", "condition", "politics"] },
  { features: ["politics", "activism", "climate", "condition"], classes: ["climate", "politics", "activism", "condition"] },
  { features: ["biology", "politics", "activism", "climate", "condition"], classes: ["climate", "politics", "activism", "condition"] },
  { features: ["nature", "condition"], classes: ["nature", "condition"] },
  { features: ["biology", "nature", "condition"], classes: ["nature", "condition"] },
  { features: ["politics", "nature", "condition"], classes: ["nature", "politics", "condition"] },
  { features: ["biology", "politics", "nature", "condition"], classes: ["nature", "politics", "condition"] },
  { features: ["activism", "nature", "condition"], classes: ["nature", "activism", "condition"] },
  { features: ["biology", "activism", "nature", "condition"], classes: ["nature", "activism", "condition"] },
  { features: ["politics", "activism", "nature", "condition"], classes: ["nature", "politics", "activism", "condition"] },
  { features: ["biology", "politics", "activism", "nature", "condition"], classes: ["nature", "politics", "activism", "condition"] },
  { features: ["climate", "nature", "condition"], classes: ["nature", "climate", "condition"] },
  { features: ["biology", "climate", "nature", "condition"], classes: ["nature", "climate", "condition"] },
  { features: ["politics", "climate", "nature", "condition"], classes: ["nature", "climate", "politics", "condition", "activism"] },
  { features: ["biology", "politics", "climate", "nature", "condition"], classes: ["nature", "climate", "politics", "condition", "activism"] },
  { features: ["activism", "climate", "nature", "condition"], classes: ["nature", "climate", "activism", "condition", "politics"] },
  { features: ["biology", "activism", "climate", "nature", "condition"], classes: ["nature", "climate", "activism", "condition", "politics"] },
  { features: ["politics", "activism", "climate", "nature", "condition"], classes: ["nature", "climate", "politics", "activism", "condition"] },
  { features: ["biology", "politics", "activism", "climate", "nature", "condition"], classes: ["nature", "climate", "politics", "activism", "condition"] }
] as { features: string[]; classes: string[] }[];
